# a6_ex2.py
from __future__ import annotations
import argparse
from pathlib import Path

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# import seaborn as sns     # optional: use seaborn for the heatmap

# ----------------------------------------------------------------------
# Figure 1: daily PM2.5 trend
# ----------------------------------------------------------------------
def plot_pm25_trend(df: pd.DataFrame) -> None:
    """
    Plot the daily average PM2.5 and save it as eda_pm25_trend.pdf.
    The DataFrame must contain the 'PM2.5' column and a DatetimeIndex
    as returned by the preprocessing step from exercise 1.
    """
    daily = df["PM2.5"].resample("D").mean()

    fig, ax = plt.subplots(figsize=(10, 4))
    ax.plot(daily.index, daily.values, linewidth=0.8)
    ax.set_title("Daily Average PM2.5")
    ax.set_xlabel("Date")
    ax.set_ylabel("PM2.5")
    fig.tight_layout()
    fig.savefig("eda_pm25_trend.pdf")
    plt.close(fig)


# ----------------------------------------------------------------------
# Figure 2: correlation heatmap
# ----------------------------------------------------------------------
def plot_correlation(df: pd.DataFrame) -> None:
    corr = df.corr(numeric_only=True)

    # Dynamic limits
    vmin = corr.values.min()
    vmax = corr.values.max()

    fig, ax = plt.subplots(figsize=(8, 6))
    im = ax.imshow(corr.values, cmap="coolwarm", vmin=vmin, vmax=vmax)

    ax.set_xticks(range(len(corr.columns)), corr.columns, rotation=90, ha="right")
    ax.set_yticks(range(len(corr.index)), corr.index)
    ax.set_title("Correlation Heatmap")

    # Annotations
    for i in range(corr.shape[0]):
        for j in range(corr.shape[1]):
            ax.text(j, i, f"{corr.iat[i, j]:.2f}",
                    ha="center", va="center", fontsize=7)

    cbar = fig.colorbar(im, ax=ax, shrink=0.8)
    cbar.ax.set_ylabel("Pearson r", rotation=-90, va="bottom")

    fig.tight_layout()
    fig.savefig("eda_correlation_heatmap.pdf")
    plt.close(fig)


# ----------------------------------------------------------------------
# Figure 3: histogram of daily average PM2.5
# ----------------------------------------------------------------------
def plot_histogram_pm25(df: pd.DataFrame) -> None:
    """
    Plot the daily average PM2.5 distribution and save it as
    eda_pm25_histogram.pdf.
    """
    daily = df["PM2.5"].resample("D").mean()
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.hist(daily.values, bins=40, edgecolor="black")
    ax.set_title("PM2.5 Histogram")
    ax.set_xlabel("PM2.5")
    ax.set_ylabel("Frequency")
    fig.tight_layout()
    fig.savefig("eda_pm25_histogram.pdf")
    plt.close(fig)


# ----------------------------------------------------------------------
# Optional: command-line execution
# ----------------------------------------------------------------------
def _cli() -> None:
    """
    Usage example:

        python a6_ex2.py --csv air_quality_cleaned.csv
    """
    parser = argparse.ArgumentParser(description="Generate EDA plots.")
    parser.add_argument(
        "--csv",
        type=Path,
        default=Path("air_quality_cleaned.csv"),
        help="Path to the cleaned CSV file (default: air_quality_cleaned.csv)",
    )
    args = parser.parse_args()

    if not args.csv.exists():
        raise FileNotFoundError(
            f"The file {args.csv} does not exist. "
            "Make sure you ran a6_ex1.py first."
        )

    df = pd.read_csv(args.csv, parse_dates=["datetime"]).set_index("datetime")

    plot_pm25_trend(df)
    plot_correlation(df)
    plot_histogram_pm25(df)
    print("Plots saved as PDF files in the current directory.")


if __name__ == "__main__":
    # Minimal example: load the CSV generated by exercise 1.
    df = (
        pd.read_csv("air_quality_cleaned.csv", parse_dates=["datetime"])
          .set_index("datetime")
    )
    plot_pm25_trend(df)
    plot_correlation(df)
    plot_histogram_pm25(df)
    print("Plots saved as PDF files in the current directory.")
